version: "3.9"

services:
  api:
    build: .
    image: localhost:32000/fastapi-argocd:latest
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
